org: madelrio
app: translate-api
service: translate-api

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    FAV_TRANSLATE_TABLE: ${self:service}-favoriteTranslations-${sls:stage}
    COGNITO_USER_POOL_ID: { Ref: CognitoUserPool }
    COGNITO_USER_POOL_CLIENT_ID: { Ref: CognitoUserPoolClient }
  httpApi:
    cors: true
    authorizers: 
      userAuthoriser:
        identitySource: $request.header.Authorization
        issuerUrl: {"Fn::Join": ["", ["https://cognito-idp.us-east-1.amazonaws.com/", { Ref: CognitoUserPool }]]}
        audience: { Ref: CognitoUserPoolClient }

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - translate:TranslateText
          Resource: '*'
        - Effect: Allow
          Action:
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminSetUserPassword
            - cognito-idp:AdminAddUserToGroup
          Resource: '*'
        - Effect: Allow
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan'
            - 'dynamodb:Query'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: 'arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-favoriteTranslations-${sls:stage}'

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-pool-${sls:stage}
        Policies:
          PasswordPolicy:
            MinimumLength: 8
        UsernameAttributes:
          - email
        Schema:
          - AttributeDataType: String
            Name: email
            Required: false
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-client-${sls:stage}
        UserPoolId:
          Ref: CognitoUserPool
        GenerateSecret: false
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - 'USER_PASSWORD_AUTH'
    FavoriteTranslationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-favoriteTranslations-${sls:stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2

functions:
  getTranslate:
    handler: src/handlers/getTranslate.getTranslateHandler
    events:
      - httpApi:
          method: post
          path: /
  register:
    handler: src/handlers/register.registerHandler
    events:
      - httpApi:
          method: post
          path: /register
  login:
    handler: src/handlers/login.loginHandler
    events:
      - httpApi:
          method: post
          path: /login
  getFavoriteUserTranslate:
    handler:  src/handlers/getFavoriteUserTranslate.getFavoriteUserTranslateHandler
    events:
      - httpApi:
          method: get
          path: /fav
          authorizer: 
            name: userAuthoriser
  addFavoriteUserTranslate:
    handler:  src/handlers/addFavoriteUserTranslate.addFavoriteUserTranslateHandler
    events:
      - httpApi:
          method: post
          path: /add
          authorizer: 
            name: userAuthoriser
  removeFavoriteUserTranslate:
    handler:  src/handlers/removeFavoriteUserTranslate.removeFavoriteUserTranslateHandler
    events:
      - httpApi:
          method: post
          path: /remove
          authorizer: 
            name: userAuthoriser
package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: false
    external:
      - '@aws-sdk/client-s3'
    exclude:
      - '@aws-sdk/*'
    packages: external
    buildConcurrency: 3
    sourcemap:
      type: linked
      setNodeOptions: true

plugins:
  - serverless-offline
